basic setup for receiving mails and clicking on them
DefactoSoftware/test_dispatch pull request #102
Opened 2021-11-12 15:00 UTC by fatboypunk

2021-11-12 15:11 UTC, EasterPeanut commented on test/support/links/_post_show.html
> +            </a>
👀

2021-11-12 16:03 UTC, EasterPeanut commented on lib/test_dispatch.ex
> +          raise("Failed to receive any email")
```suggestion
```

2021-11-12 16:04 UTC, EasterPeanut commented on lib/test_dispatch.ex
> +
```suggestion
```

2021-11-16 11:30 UTC, fatboypunk commented on README.md
> +A library that adds the ability to use controller tests as integration tests
```suggestion
TestDispatch adds the ability to use controller tests as integration tests
```

2021-11-16 11:31 UTC, fatboypunk commented on README.md
> +## Clicking on links in mails
```suggestion
### Clicking on links in mails
```

2021-11-16 11:31 UTC, fatboypunk commented on guides/testing-with-test-dispatch.md
> +
```suggestion
```

2021-11-16 12:17 UTC, EasterPeanut requested changes

2021-11-16 12:17 UTC, EasterPeanut commented on test/receive_emeail_test.exs
> +    test "receive email with expected_fields:: [subject, to]", %{conn: conn} do
```suggestion
    test "receive email with expected_fields: [subject, to]", %{conn: conn} do
```

2021-11-16 12:17 UTC, EasterPeanut commented on test/receive_emeail_test.exs
> +    test "receive email with expected_fields:: [subject, from]", %{conn: conn} do
```suggestion
    test "receive email with expected_fields: [subject, from]", %{conn: conn} do
```

2021-11-16 12:17 UTC, EasterPeanut commented on test/receive_emeail_test.exs
> +    test "receive email with expected_fields:: [to, from]", %{conn: conn} do
```suggestion
    test "receive email with expected_fields: [to, from]", %{conn: conn} do
```

2021-11-16 12:17 UTC, EasterPeanut commented on test/receive_emeail_test.exs
> +    test "receive email with expected_fields:: [from]", %{conn: conn} do
```suggestion
    test "receive email with expected_fields: [from]", %{conn: conn} do
```

2021-11-16 12:17 UTC, EasterPeanut commented on test/receive_emeail_test.exs
> +    test "receive email with expected_fields:: [to]", %{conn: conn} do
```suggestion
    test "receive email with expected_fields: [to]", %{conn: conn} do
```

2021-11-16 12:17 UTC, EasterPeanut commented on test/receive_emeail_test.exs
> +    test "receive email with expected_fields:: [subject]", %{conn: conn} do
```suggestion
    test "receive email with expected_fields: [subject]", %{conn: conn} do
```

2021-11-16 12:17 UTC, EasterPeanut commented
just grammar things

2021-11-16 12:31 UTC, fatboypunk commented on guides/testing-with-test-dispatch.md
> +the link in an email.
```suggestion
the found email will be added to the conn as the `resp_body`. Using the conn
combined with the `click_link/4` function you can simulate "clicking" on the
link in an email.
```

2021-11-16 12:45 UTC, EasterPeanut approved these changes

2021-11-16 12:53 UTC, merged